/// Flutter icons EquipeIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EquipeIcons
///      fonts:
///       - asset: fonts/EquipeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EquipeIcons {
  EquipeIcons._();

  static const _kFontFam = 'EquipeIcons';
  static const String? _kFontPkg = null;

  static const IconData logo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
